# Local server to test setup.py
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20180917.0.0"
  config.vm.hostname = "ubuntu-1804.local"
  config.vm.network "private_network", ip: "192.168.33.11"
end
